### PR TITLE
Fix dockerignore to pass auto folder

### PR DESCRIPTION
**Pull request by joao-p-marques**

### CODE REVIEW

**Comment by Yajo** [comment]
Push this to stable and release ASAP.

**Review by Yajo — APPROVED** [review]

**Comment by joao-p-marques** [comment]
@Yajo I think you have to merge here

**Comment by Yajo** [comment]
Done, please release

**Comment by joao-p-marques** [comment]
Done in 
<https://github.com/Tecnativa/doodba-copier-template/releases/tag/v2.7.1>

**Pull request merged**
