### PR TITLE
build(vscode): don't ignore settings, extensions, tasks...

### PR DESCRIPTION
**Pull request by yajo**
Before this patch, extension recommendations were no longer being propagated automatically to subprojects.

@moduon MT-2532

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Can you explain why this patch fixes that?

**Comment by yajo** [comment]
I guess that at some point Git started processing these ignore lines in order. So you first have to add the ignores and later add the exclusions. It's easy to reproduce:

```shell
➤ copier -f copy https://github.com/Tecnativa/doodba-copier-template a
Copying from template version 5.1.3
    create  .
    create  README.md
    create  .pre-commit-config.yaml
    create  .copier-answers.yml
    create  LICENSE
    create  test.yaml
    create  tasks.py
    create  setup-devel.yaml
    create  prod.yaml
    create  odoo
    create  odoo/custom
    create  odoo/custom/ssh
    create  odoo/custom/ssh/known_hosts
    create  odoo/custom/ssh/id_rsa.pub
    create  odoo/custom/ssh/id_rsa
    create  odoo/custom/ssh/config
    create  odoo/custom/src
    create  odoo/custom/src/repos.yaml
    create  odoo/custom/src/private
    create  odoo/custom/src/private/.editorconfig
    create  odoo/custom/src/addons.yaml
    create  odoo/custom/entrypoint.d
    create  odoo/custom/entrypoint.d/.empty
    create  odoo/custom/dependencies
    create  odoo/custom/dependencies/pip.txt
    create  odoo/custom/dependencies/npm.txt
    create  odoo/custom/dependencies/gem.txt
    create  odoo/custom/dependencies/apt_build.txt
    create  odoo/custom/dependencies/apt.txt
    create  odoo/custom/conf.d
    create  odoo/custom/conf.d/.empty
    create  odoo/custom/build.d
    create  odoo/custom/build.d/.empty
    create  odoo/Dockerfile
    create  odoo/.dockerignore
    create  devel.yaml
    create  common.yaml
    create  .vscode
    create  .vscode/extensions.json
    create  .vscode/doodba.code-snippets
    create  .pylintrc
    create  .pylintrc-mandatory
    create  .prettierrc.yml
    create  .isort.cfg
    create  .gitignore
    create  .flake8
    create  .eslintrc.yml
    create  .editorconfig
    create  .docker
    create  .docker/odoo.env
    create  .docker/db-creation.env
    create  .docker/db-access.env

 > Running task 1 of 2: invoke after-update
 > Running task 2 of 2: invoke develop
Inicializado repositorio Git vacío en /tmp/a/.git/
pre-commit installed at .git/hooks/pre-commit

➤ git -C a status --porcelain
?? .copier-answers.yml
?? .editorconfig
?? .eslintrc.yml
?? .flake8
?? .gitignore
?? .isort.cfg
?? .pre-commit-config.yaml
?? .prettierrc.yml
?? .pylintrc
?? .pylintrc-mandatory
?? LICENSE
?? README.md
?? common.yaml
?? devel.yaml
?? odoo/
?? prod.yaml
?? setup-devel.yaml
?? tasks.py
?? test.yaml

➤ copier -f -r no-ignore-settings copy https://github.com/moduon/doodba-copier-template b
Copying from template version 5.1.3.post1.dev0+3afaa97
    create  .
    create  .copier-answers.yml
    create  LICENSE
    create  test.yaml
    create  tasks.py
    create  setup-devel.yaml
    create  prod.yaml
    create  odoo
    create  odoo/custom
    create  odoo/custom/ssh
    create  odoo/custom/ssh/known_hosts
    create  odoo/custom/ssh/id_rsa.pub
    create  odoo/custom/ssh/id_rsa
    create  odoo/custom/ssh/config
    create  odoo/custom/src
    create  odoo/custom/src/repos.yaml
    create  odoo/custom/src/private
    create  odoo/custom/src/private/.editorconfig
    create  odoo/custom/src/addons.yaml
    create  odoo/custom/entrypoint.d
    create  odoo/custom/entrypoint.d/.empty
    create  odoo/custom/dependencies
    create  odoo/custom/dependencies/pip.txt
    create  odoo/custom/dependencies/npm.txt
    create  odoo/custom/dependencies/gem.txt
    create  odoo/custom/dependencies/apt_build.txt
    create  odoo/custom/dependencies/apt.txt
    create  odoo/custom/conf.d
    create  odoo/custom/conf.d/.empty
    create  odoo/custom/build.d
    create  odoo/custom/build.d/.empty
    create  odoo/Dockerfile
    create  odoo/.dockerignore
    create  devel.yaml
    create  common.yaml
    create  README.md
    create  .vscode
    create  .vscode/extensions.json
    create  .vscode/doodba.code-snippets
    create  .pylintrc
    create  .pylintrc-mandatory
    create  .prettierrc.yml
    create  .pre-commit-config.yaml
    create  .isort.cfg
    create  .gitignore
    create  .flake8
    create  .eslintrc.yml
    create  .editorconfig
    create  .docker
    create  .docker/odoo.env
    create  .docker/db-creation.env
    create  .docker/db-access.env

 > Running task 1 of 2: invoke after-update
 > Running task 2 of 2: invoke develop
Inicializado repositorio Git vacío en /tmp/b/.git/
pre-commit installed at .git/hooks/pre-commit

➤ git -C b status --porcelain
?? .copier-answers.yml
?? .editorconfig
?? .eslintrc.yml
?? .flake8
?? .gitignore
?? .isort.cfg
?? .pre-commit-config.yaml
?? .prettierrc.yml
?? .pylintrc
?? .pylintrc-mandatory
?? .vscode/
?? LICENSE
?? README.md
?? common.yaml
?? devel.yaml
?? odoo/
?? prod.yaml
?? setup-devel.yaml
?? tasks.py
?? test.yaml
```

You can see that the line `?? .vscode/` only appear when copying the template with this patch included.

**Review by pedrobaeza — APPROVED** [review]

**Comment by yajo** [comment]
Would you mind to do a new release including all new fixes please?

**Comment by pedrobaeza** [comment]
Done. Sorry for the delay. I wanted to include it the PG patch also, but let's have it and we will release later when available.

https://github.com/Tecnativa/doodba-copier-template/releases/tag/v5.1.4

**Pull request merged**
