### PR TITLE
[FIX] The SMTP domain should prefix `smtp`

### PR DESCRIPTION
**Pull request by pedrobaeza**
If not, mails are not delivered.

@Tecnativa

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Well, I'm not experiencing the same, so better to let it as it was, unless you have any side-effect that let you to change this.

**Comment by Tardo** [comment]
No problem. The only thing is the issue of having the 'smtp' part hardcoded... but I don't see a major problem either.

Maybe are matching 'smtp_canonical_default' with the hostname of the odoo service?

**Comment by pedrobaeza** [comment]
Yes, I think it has to be with the docker internal naming scheme, not being able to route from  `odoo` container to `smtp` container. As I'm not sure how to fix it, let's go to the hardcoded thing.

**Comment by Tardo** [comment]
Ok, my apologies for my mistake

**Comment by pedrobaeza** [comment]
No worries. It has been detected soon enough.

**Pull request merged**
