### PR TITLE
fix typo in backups

### PR DESCRIPTION
**Pull request by ap-wtioit**

### CODE REVIEW

**Review by joao-p-marques — APPROVED** [review]

**Comment by joao-p-marques** [comment]
Thanks for the correction @ap-wtioit :smiley:

**Review by Yajo — APPROVED** [review]

**Comment by ap-wtioit** [comment]
test errors seem related to https://twitter.com/Scott_Helme/status/1443604252501417984

**Comment by joao-p-marques** [comment]
Indeed... We are already looking for a fix. You can follow the process 
in <https://github.com/Tecnativa/doodba-copier-template/issues/278>

Once it is fixed, you can rebase here...

**Comment by Yajo** [comment]
v10 should get out of support this week, so in case we don't get a fix in time, this could be rebased after removing that support.

**Comment by joao-p-marques** [comment]
> v10 should get out of support this week, so in case we don't get a fix in time, this could be rebased after removing that support.

True :)

Anyway, once https://github.com/Tecnativa/doodba-copier-template/pull/279 is merged, you can rebase here to fix the issue to avoid the wait...

**Comment by Yajo** [comment]
May you rebase please?

**Pull request merged**
