### PR TITLE
feat: generate private addon readmes with markdown fragments

### PR DESCRIPTION
**Pull request by yajo**
Adds support for the latest changes found in maintainer tools.

Now, readmes will have a source digest, resulting in fewer rebuilds, and markdown portions are supported.

### CODE REVIEW

**Review by chienandalu — APPROVED** [review]
thanks! :+1: (although tests are :-1: )

**Comment by yajo** [comment]
The failure is in the main branch. https://github.com/Tecnativa/doodba-copier-template/pull/403 was merged with the same failure included.

**Comment by yajo** [comment]
I rebased, now that the main branch is green.

**Comment by pedrobaeza** [comment]
Can you please check the CI error?

**Comment by yajo** [comment]
I think it should be fixed now.

**Review by pedrobaeza — APPROVED** [review]
Don't know syntax exactly, but I trust you :)

**Pull request merged**
