### PR TITLE
feat: add module readme generator

### PR DESCRIPTION
**Pull request by yajo**
This allows doodba private modules to benefit from having a generated readme.

The template is pretty similar to the one in https://github.com/OCA/maintainer-tools, but it removes all OCA-specific stuff, making it more suitable for doodba.

@moduon MT-956 https://github.com/OCA/maintainer-tools/pull/557

### CODE REVIEW

**Comment by yajo** [comment]
Not in this case, as this template is almost completely different to OCA's. However there were some tests failing that should be fixed now.

**Comment by yajo** [comment]
The CI failure is not related to this PR

**Comment by pedrobaeza** [comment]
Not sure what can happen. Can you give me any idea?

**Comment by yajo** [comment]
I opened https://github.com/Tecnativa/doodba-copier-template/issues/374 to keep both issues focused 😊

**Comment by yajo** [comment]
I see that #375 went ✅  so maybe it was just a temporary failure. I rebased; let's see...

**Comment by yajo** [comment]
Coool, it's green now!

**Pull request merged**
